// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/DataType.proto

package com.jiayoo.proto;

public final class MyDataInfo {
  private MyDataInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jiayoo.protobuf.MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.jiayoo.protobuf.MyMessage.DataType data_type = 1;</code>
     */
    boolean hasDataType();
    /**
     * <code>optional .com.jiayoo.protobuf.MyMessage.DataType data_type = 1;</code>
     */
    com.jiayoo.proto.MyDataInfo.MyMessage.DataType getDataType();

    /**
     * <code>optional .com.jiayoo.protobuf.MyMessage.ResponseType response_type = 2;</code>
     */
    boolean hasResponseType();
    /**
     * <code>optional .com.jiayoo.protobuf.MyMessage.ResponseType response_type = 2;</code>
     */
    com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType getResponseType();

    /**
     * <code>optional string message = 3;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code com.jiayoo.protobuf.MyMessage}
   */
  public  static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jiayoo.protobuf.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      dataType_ = 1;
      responseType_ = 1;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.jiayoo.proto.MyDataInfo.MyMessage.DataType value = com.jiayoo.proto.MyDataInfo.MyMessage.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataType_ = rawValue;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType value = com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                responseType_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              message_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jiayoo.proto.MyDataInfo.internal_static_com_jiayoo_protobuf_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jiayoo.proto.MyDataInfo.internal_static_com_jiayoo_protobuf_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jiayoo.proto.MyDataInfo.MyMessage.class, com.jiayoo.proto.MyDataInfo.MyMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code com.jiayoo.protobuf.MyMessage.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LoginType = 1;</code>
       */
      LoginType(1),
      /**
       * <code>RegisterType = 2;</code>
       */
      RegisterType(2),
      /**
       * <code>ChangePassType = 3;</code>
       */
      ChangePassType(3),
      /**
       * <code>AddFriendType = 4;</code>
       */
      AddFriendType(4),
      /**
       * <code>DeleteFriendType = 5;</code>
       */
      DeleteFriendType(5),
      /**
       * <code>AddGroupType = 6;</code>
       */
      AddGroupType(6),
      /**
       * <code>DeleteGroupType = 7;</code>
       */
      DeleteGroupType(7),
      ;

      /**
       * <code>LoginType = 1;</code>
       */
      public static final int LoginType_VALUE = 1;
      /**
       * <code>RegisterType = 2;</code>
       */
      public static final int RegisterType_VALUE = 2;
      /**
       * <code>ChangePassType = 3;</code>
       */
      public static final int ChangePassType_VALUE = 3;
      /**
       * <code>AddFriendType = 4;</code>
       */
      public static final int AddFriendType_VALUE = 4;
      /**
       * <code>DeleteFriendType = 5;</code>
       */
      public static final int DeleteFriendType_VALUE = 5;
      /**
       * <code>AddGroupType = 6;</code>
       */
      public static final int AddGroupType_VALUE = 6;
      /**
       * <code>DeleteGroupType = 7;</code>
       */
      public static final int DeleteGroupType_VALUE = 7;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 1: return LoginType;
          case 2: return RegisterType;
          case 3: return ChangePassType;
          case 4: return AddFriendType;
          case 5: return DeleteFriendType;
          case 6: return AddGroupType;
          case 7: return DeleteGroupType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.jiayoo.proto.MyDataInfo.MyMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.jiayoo.protobuf.MyMessage.DataType)
    }

    /**
     * Protobuf enum {@code com.jiayoo.protobuf.MyMessage.ResponseType}
     */
    public enum ResponseType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LoginSuccess = 1;</code>
       */
      LoginSuccess(1),
      /**
       * <code>RegisterSuccess = 2;</code>
       */
      RegisterSuccess(2),
      /**
       * <code>ChangePassSuccess = 3;</code>
       */
      ChangePassSuccess(3),
      /**
       * <code>AddFriendTypeSuccess = 4;</code>
       */
      AddFriendTypeSuccess(4),
      /**
       * <code>DeleteFriendSuccess = 5;</code>
       */
      DeleteFriendSuccess(5),
      /**
       * <code>AddGroupSuccess = 6;</code>
       */
      AddGroupSuccess(6),
      /**
       * <code>DeleteGroupSuccess = 7;</code>
       */
      DeleteGroupSuccess(7),
      ;

      /**
       * <code>LoginSuccess = 1;</code>
       */
      public static final int LoginSuccess_VALUE = 1;
      /**
       * <code>RegisterSuccess = 2;</code>
       */
      public static final int RegisterSuccess_VALUE = 2;
      /**
       * <code>ChangePassSuccess = 3;</code>
       */
      public static final int ChangePassSuccess_VALUE = 3;
      /**
       * <code>AddFriendTypeSuccess = 4;</code>
       */
      public static final int AddFriendTypeSuccess_VALUE = 4;
      /**
       * <code>DeleteFriendSuccess = 5;</code>
       */
      public static final int DeleteFriendSuccess_VALUE = 5;
      /**
       * <code>AddGroupSuccess = 6;</code>
       */
      public static final int AddGroupSuccess_VALUE = 6;
      /**
       * <code>DeleteGroupSuccess = 7;</code>
       */
      public static final int DeleteGroupSuccess_VALUE = 7;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseType valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseType forNumber(int value) {
        switch (value) {
          case 1: return LoginSuccess;
          case 2: return RegisterSuccess;
          case 3: return ChangePassSuccess;
          case 4: return AddFriendTypeSuccess;
          case 5: return DeleteFriendSuccess;
          case 6: return AddGroupSuccess;
          case 7: return DeleteGroupSuccess;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResponseType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
              public ResponseType findValueByNumber(int number) {
                return ResponseType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.jiayoo.proto.MyDataInfo.MyMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final ResponseType[] VALUES = values();

      public static ResponseType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResponseType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.jiayoo.protobuf.MyMessage.ResponseType)
    }

    private int bitField0_;
    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>optional .com.jiayoo.protobuf.MyMessage.DataType data_type = 1;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.jiayoo.protobuf.MyMessage.DataType data_type = 1;</code>
     */
    public com.jiayoo.proto.MyDataInfo.MyMessage.DataType getDataType() {
      @SuppressWarnings("deprecation")
      com.jiayoo.proto.MyDataInfo.MyMessage.DataType result = com.jiayoo.proto.MyDataInfo.MyMessage.DataType.valueOf(dataType_);
      return result == null ? com.jiayoo.proto.MyDataInfo.MyMessage.DataType.LoginType : result;
    }

    public static final int RESPONSE_TYPE_FIELD_NUMBER = 2;
    private int responseType_;
    /**
     * <code>optional .com.jiayoo.protobuf.MyMessage.ResponseType response_type = 2;</code>
     */
    public boolean hasResponseType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.jiayoo.protobuf.MyMessage.ResponseType response_type = 2;</code>
     */
    public com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType getResponseType() {
      @SuppressWarnings("deprecation")
      com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType result = com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType.valueOf(responseType_);
      return result == null ? com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType.LoginSuccess : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <code>optional string message = 3;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dataType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, responseType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, responseType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jiayoo.proto.MyDataInfo.MyMessage)) {
        return super.equals(obj);
      }
      com.jiayoo.proto.MyDataInfo.MyMessage other = (com.jiayoo.proto.MyDataInfo.MyMessage) obj;

      boolean result = true;
      result = result && (hasDataType() == other.hasDataType());
      if (hasDataType()) {
        result = result && dataType_ == other.dataType_;
      }
      result = result && (hasResponseType() == other.hasResponseType());
      if (hasResponseType()) {
        result = result && responseType_ == other.responseType_;
      }
      result = result && (hasMessage() == other.hasMessage());
      if (hasMessage()) {
        result = result && getMessage()
            .equals(other.getMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataType()) {
        hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + dataType_;
      }
      if (hasResponseType()) {
        hash = (37 * hash) + RESPONSE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + responseType_;
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jiayoo.proto.MyDataInfo.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jiayoo.proto.MyDataInfo.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jiayoo.protobuf.MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jiayoo.protobuf.MyMessage)
        com.jiayoo.proto.MyDataInfo.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jiayoo.proto.MyDataInfo.internal_static_com_jiayoo_protobuf_MyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jiayoo.proto.MyDataInfo.internal_static_com_jiayoo_protobuf_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jiayoo.proto.MyDataInfo.MyMessage.class, com.jiayoo.proto.MyDataInfo.MyMessage.Builder.class);
      }

      // Construct using com.jiayoo.proto.MyDataInfo.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jiayoo.proto.MyDataInfo.internal_static_com_jiayoo_protobuf_MyMessage_descriptor;
      }

      @java.lang.Override
      public com.jiayoo.proto.MyDataInfo.MyMessage getDefaultInstanceForType() {
        return com.jiayoo.proto.MyDataInfo.MyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.jiayoo.proto.MyDataInfo.MyMessage build() {
        com.jiayoo.proto.MyDataInfo.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jiayoo.proto.MyDataInfo.MyMessage buildPartial() {
        com.jiayoo.proto.MyDataInfo.MyMessage result = new com.jiayoo.proto.MyDataInfo.MyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataType_ = dataType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseType_ = responseType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jiayoo.proto.MyDataInfo.MyMessage) {
          return mergeFrom((com.jiayoo.proto.MyDataInfo.MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jiayoo.proto.MyDataInfo.MyMessage other) {
        if (other == com.jiayoo.proto.MyDataInfo.MyMessage.getDefaultInstance()) return this;
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        if (other.hasResponseType()) {
          setResponseType(other.getResponseType());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000004;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jiayoo.proto.MyDataInfo.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jiayoo.proto.MyDataInfo.MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dataType_ = 1;
      /**
       * <code>optional .com.jiayoo.protobuf.MyMessage.DataType data_type = 1;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.jiayoo.protobuf.MyMessage.DataType data_type = 1;</code>
       */
      public com.jiayoo.proto.MyDataInfo.MyMessage.DataType getDataType() {
        @SuppressWarnings("deprecation")
        com.jiayoo.proto.MyDataInfo.MyMessage.DataType result = com.jiayoo.proto.MyDataInfo.MyMessage.DataType.valueOf(dataType_);
        return result == null ? com.jiayoo.proto.MyDataInfo.MyMessage.DataType.LoginType : result;
      }
      /**
       * <code>optional .com.jiayoo.protobuf.MyMessage.DataType data_type = 1;</code>
       */
      public Builder setDataType(com.jiayoo.proto.MyDataInfo.MyMessage.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.jiayoo.protobuf.MyMessage.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 1;
        onChanged();
        return this;
      }

      private int responseType_ = 1;
      /**
       * <code>optional .com.jiayoo.protobuf.MyMessage.ResponseType response_type = 2;</code>
       */
      public boolean hasResponseType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.jiayoo.protobuf.MyMessage.ResponseType response_type = 2;</code>
       */
      public com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType getResponseType() {
        @SuppressWarnings("deprecation")
        com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType result = com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType.valueOf(responseType_);
        return result == null ? com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType.LoginSuccess : result;
      }
      /**
       * <code>optional .com.jiayoo.protobuf.MyMessage.ResponseType response_type = 2;</code>
       */
      public Builder setResponseType(com.jiayoo.proto.MyDataInfo.MyMessage.ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        responseType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.jiayoo.protobuf.MyMessage.ResponseType response_type = 2;</code>
       */
      public Builder clearResponseType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseType_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 3;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jiayoo.protobuf.MyMessage)
    }

    // @@protoc_insertion_point(class_scope:com.jiayoo.protobuf.MyMessage)
    private static final com.jiayoo.proto.MyDataInfo.MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jiayoo.proto.MyDataInfo.MyMessage();
    }

    public static com.jiayoo.proto.MyDataInfo.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @java.lang.Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jiayoo.proto.MyDataInfo.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jiayoo_protobuf_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jiayoo_protobuf_MyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033src/protobuf/DataType.proto\022\023com.jiayo" +
      "o.protobuf\"\335\003\n\tMyMessage\022:\n\tdata_type\030\001 " +
      "\001(\0162\'.com.jiayoo.protobuf.MyMessage.Data" +
      "Type\022B\n\rresponse_type\030\002 \001(\0162+.com.jiayoo" +
      ".protobuf.MyMessage.ResponseType\022\017\n\007mess" +
      "age\030\003 \001(\t\"\217\001\n\010DataType\022\r\n\tLoginType\020\001\022\020\n" +
      "\014RegisterType\020\002\022\022\n\016ChangePassType\020\003\022\021\n\rA" +
      "ddFriendType\020\004\022\024\n\020DeleteFriendType\020\005\022\020\n\014" +
      "AddGroupType\020\006\022\023\n\017DeleteGroupType\020\007\"\254\001\n\014" +
      "ResponseType\022\020\n\014LoginSuccess\020\001\022\023\n\017Regist" +
      "erSuccess\020\002\022\025\n\021ChangePassSuccess\020\003\022\030\n\024Ad" +
      "dFriendTypeSuccess\020\004\022\027\n\023DeleteFriendSucc" +
      "ess\020\005\022\023\n\017AddGroupSuccess\020\006\022\026\n\022DeleteGrou" +
      "pSuccess\020\007B \n\020com.jiayoo.protoB\nMyDataIn" +
      "foH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jiayoo_protobuf_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jiayoo_protobuf_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jiayoo_protobuf_MyMessage_descriptor,
        new java.lang.String[] { "DataType", "ResponseType", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
